config/routes.rb
TheBoxNoir::Application.routes.draw do

	root to: "welcome#index"
	
	get '/reserve', :to => 'welcome#reserve'
	get '/login', :to => 'session#new'
  
  
  get '/about', :to => 'about#index'
	get '/faq', :to => 'about#faq'
	get '/careers', :to => 'about#careers'
  
    resources :reference
	resources :users
	resources :products
	
	resources :waitlists

	resources :session

  

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password validations: false #Validations for presence of password on create, confirmation of password (using a password_confirmation attribute) are automatically added. If you wish to turn off validations, pass validations: false as an argument. You can add more validations by hand if need be. 

	validates :password,
		:length => {:in => 5..30},
		:format => {:with => /\A\S*$\z/},
		:presence => {:on => :create}
end

app/models/waitlist.rb
class Waitlist < ActiveRecord::Base

#serialize :gender, :type


validates :email_address,
	presence: true,
	uniqueness: true,
	format: {with: /\A.+@.+\..+/}

validates :gender,
	presence: false,
	inclusion: { in: %w(male female) },
	allow_nil: true
	
validates :type,
  presence: true,
  inclusion: { in: %w(winebox beerbox ctailbox) },
  allow_nil: true
	
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout 'about'
  
  def index
  end
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
  end
end

app/controllers/reference_controller.rb
class ReferenceController < ApplicationController


    def index
        @name = 'VIVIAN XUE'
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

def create
  user = User.find_by_email_address(params[:session][:email_address])
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
		redirect_to :back
  else
    flash.now[:alert] = "Invalid email or password"
    render "new"
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
end

def create
end

end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController

def create
  wait = Waitlist.create(params[:waitlist].permit(:email_address, :gender, :type))
  
  if request.xhr?
    
    if wait.save
			WaitlistMailer.delay.welcome_email(wait) #send email
      render status: 200, :json => {:success => 'ok'}
    else
      render status: 406, :json => {:error => wait.errors.full_messages}
    end
    
  else
    redirect_to :back
  end

end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  
  def index
		@waitlist = Waitlist.new
  end
  def reserve
		@waitlist = Waitlist.new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reference_helper.rb
module ReferenceHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/careers.html.erb
<% content_for(:title, 'Careers: The Box Noir') %>

<div class="col-xs-12 col-sm-9">
  <div id="about-jumbotron" class="jumbotron">
		<%= image_tag('careers.png')%>
  </div>
	<div id="about-page-header" class="page-header">
		<p>We're looking for folks who share our vision. You're not an employee, you're a part of our family.</p>
	</div>
	<div class="about-page-body page-header">
		<h4>Experience Director</h4>
		<p>We're looking for someone who knows their way around the bar. The experience director is primarily responsible for curating monthly subscription boxes. The ideal candidates are enthusiasts and experts about either wine, beer, or spirits. Experience in the beverage industry is strongly preferred. Apply with resume/cover letter or LinkedIn.</p>
	</div>
	<div class="about-page-body page-header">
		<h4>Sales Director</h4>
		<p>The sales director is responsible for maintaining and creating new retail partnerships for the Box Noir. The ideal candidates should be experienced with scaling businesses and have a strong sales background. Advanced degrees preferred. Apply with resume/cover letter or LinkedIn.</p>
	</div>
	<div class="about-page-body page-header">
		<h4>Marketing Director</h4>
		<p>The marketing director is responsible for creating campaigns for marketing any products shipped by Box Noir. Ideal candidates should be experienced with public relations, marketing products, and even graphic design. Apply with resume/cover letter or LinkedIn.</p>
	</div>
	<div class="about-page-body page-header">
		<h4>Customer Service Rep</h4>
		<p>Customer service representatives will work to troubleshoot all issues relating to customer transactions, shipments, cancellations, refunds, etc. Experience in customer service is required. Apply with resume/cover letter or LinkedIn.</p>
	</div>
	<div class="about-page-body page-header" style="border-bottom:none;">
		<p>Apply via <a href="mailto:jobs@theboxnoir.com">jobs@theboxnoir.com</a>.</p>
	</div>
	<br />
	<br />
	<br />
</div>

app/views/about/faq.html.erb
<% content_for(:title, 'FAQ: The Box Noir') %>

<div class="col-xs-12 col-sm-9">
	<div id="about-page-header" class="page-header">
		<h2>Frequently Asked Questions</h2>
	</div>
	<div class="about-page-body page-header">
		<h3>I just reserved my Box Noir. What happens now?</h3>
		<br />
		<p>Thanks for your reservation! Because Box Noir is a small shop, we make our boxes to order. A short wait later, we'll shoot you an email with instructions when your box is ready to purchase.</p>
	</div>
	<div class="about-page-body page-header">
		<h3>What should I expect to receive in my Box Noir?</h3>
		<br />
		<p>Depending on the kind of subscription you have purchased, you will either receive a minimum of 3 bottles of wine, 6 bottles of beer, or 2 cocktail (recipes + basic ingredients) with one wine and one beer. Because each Box Noir is themed, you can expect seasonal surprises in your box like barware, snacks to go with your drink, and keepsake historical context about what you're drinking. Your very first Box Noir will always include Noir's Guide to Drinking (a handy guidebook of bar terms). </p>
	</div>
	<div class="about-page-body page-header">
		<h3>When can I cancel my subscription?</h3>
		<br />
		<p>You can cancel month to month subscriptions any time you like. If you do sign up for longer subscription, you'll be able to cancel the subscription either before the first box is shipped or after the last box is shipped.</p>
	</div>
	<div class="about-page-body page-header">
		<h3>Once I subscribe, can I change my subscription type?</h3>
		<br />
		<p>You may change your subscription type only if you have signed up for that type on a month to month basis. We recommend that our more agnostic customers to try the cocktail subscription. The cocktail subscription is the only box that includes a truly assorted collection of alcohol.</p>
	</div>
	<div class="about-page-body page-header">
		<h3>What is your refund or cancellation policy?</h3>
		<br />
		<p>Unfortunately, we do not provide refunds or exchanges. In the event of any damage, however, please feel free to contact customer service at our toll free number and we'll be happy to ship you a replacement box.
			<br />
			Cancellations on month to month subscriptions are free. On non-month to month subscriptions, premature cancellation will incur a $20 cancellation fee. 
		</p>
	</div>
	<br />
	<br />
	<br />
	<br />
	
</div>

app/views/about/index.html.erb
<% content_for(:title, 'About: The Box Noir') %>

<div class="col-xs-12 col-sm-9">
  <div id="about-jumbotron" class="jumbotron">
		<%= image_tag('about.png')%>
  </div>
	<div id="about-page-header" class="page-header">
		<p>The Box Noir was founded to make the experience of drinking better in every way imaginable.</p>
	</div>
	<div id="about-page-founders">
		<%= image_tag('vivian.png')%>
		<span id="founders">
			<p>
				<b><i>Vivian Xue</i></b> <br />
				Founder + CEO @ The Box Noir<br />
				Twitter: <a href="http://twitter.com/vivianwxue" rel="no_follow" target="_BLANK">@vivianwxue</a><br />
				<a href="mailto:vivian@theboxnoir.com" rel="no_follow">vivian (at) theboxnoir.com</a>
			</p>
		</span>
	</div>
	<p class="about-page-body">
	On her 21st birthday, Vivian Xue made a lofty resolution to try every alcoholic beverage on the planet. She wanted to order drinks like James Bond did in Casino Royale and talk about wines and whiskeys like a pro. Honoring this resolution became incredibly costly on a college budget. A few disappointing bottles of vodka later, Vivian abandoned her goal and was forced to play it safe with mojitos and grocery store moscato d'asti. A whole year later, Vivian heard a colleague joke about a lame business model "like Birchbox for alcohol". She took the lame business model and ran with it, secretly ecstatic about the second chance she had at finally staying true to her resolution. Equipped with 2 of the best advisers and engineers, the Box Noir was born. 
	<br />
	<br /s>
	The Box Noir offers more than a subscription. We offer an experience through the art of drinking. Every box is either a lesson in flavor, in history, or in culture. Because we're a small shop, we make every box to order. If you're even remotely interested in even the idea of drinking, please reserve your box today. Choose the subscription you'd like to reserve. No obligation and no payment until we're ready to ship your first box. 
	</p>
	<div class="about-turn turn">
		<div class="row">
			<div class="col-lg-4">
				<div class="col-container">
					<div class="col-header">the original box noir</div>
			     <span class="col-ic col-ctail"></span>
					<div class="col-bottom">
						<%= link_to(reserve_url) do %>		
							<span class="btn btn-info">Reserve this Box</span>
						<% end %>
					</div>
				</div>
		  </div>
	  <div class="col-lg-4">
			<div class="col-container">
			<div class="col-header">wine subscription</div>
	     <span class="col-ic col-wine"></span>
			<div class="col-bottom">
				<%= link_to(reserve_url) do %>		
					<span class="btn btn-info">Reserve this Box</span>
				<% end %>					
			</div>
		</div>
	  </div>
	  <div class="col-lg-4">
		<div class="col-container">
			<div class="col-header">beer subscription</div>
	     <span class="col-ic col-beer"></span>
			<div class="col-bottom">
				<%= link_to(reserve_url) do %>		
					<span class="btn btn-info">Reserve this Box</span>
				<% end %>
			</div>
		</div>
	 	</div>

	</div>
	</div>
</div>

app/views/products/index.html.erb
<div class="container">
	<div class="general-form">
		<h1>Manage addresses</h1>
		<p>Manage addresses for all your purchases in the BD Shop</p>
		<span class="button gray_button">Add new address</span>		
	</div>
</div>

app/views/reference/index.html.erb
<div>HELLO REFERENCE with <%= @name %></div>

app/views/session/new.html.erb
<% content_for(:title, 'Login: The Box Noir') %>



<%= form_for(:session, :url => session_index_path, :html => {:class => 'form-signin'}, :method => :post) do |f| %>
	<h2 class="form-signin-heading"><b>Welcome back,</b> old friend.</h2>
		<% if flash %>
			<% flash.each do |key, notice| %>
				<span><span><% key %></span><%= notice %></span>
			<% end %>
		<% end %>
		<%= f.email_field(:email_address, :class => 'form-control', :autofocus => 'autofocus') %>
		<%= f.password_field(:password, :class => 'form-control') %>
		<%= f.label(:remember_me, :class => 'checkbox') do %>
			<%= f.check_box(:remember_me, :checked => 'checked') %>
			Remember Me
		<% end %>
	<%= f.submit('Login', :name => nil, :class => 'btn btn-lg btn-primary btn-block') %>
<% end %>

app/views/welcome/index.html.erb
<script>
	$(function(){
		var images = ['idx_first_1.jpg', 'idx_first_2.jpg', 'idx_first_3.jpg', 'idx_first_4.jpg', 'idx_first_5.jpg'];
		$('#backdrop').css({'background-image': 'image-url(assets/' + images[Math.floor(Math.random() * images.length)] + ')'});
	});
</script>

<%= render(:partial => 'partials/bar') -%>

<div id="backdrop">
	<div class="navbar navbar-opaque">
		<div class="container">
			<%= link_to(root_url) do %>
				<%= image_tag('logo.png', :id => 'nav-logo')%>
			<% end %>
	  </div>
	</div>
  <div class="jumbotron">
    <div class="container">
			<%= image_tag('pitch.png', :id => 'pitch-banner')%>
			<div id="jumbotron-pitch">
			<form action="<%= reserve_path %>" method="get" >
				 <%= email_field_tag :email, nil, class: 'form-control', placeholder: 'your email address' %>
				 <%= submit_tag "reserve my box", class: 'btn btn-primary btn-lg', name: nil %>
			</form>
			</div>
			<div id="jumbotron-promo">
				<span class="sprite-discount"></span>
				<p><b>Free shipping</b> on every order. <b>Reserve your box</b> today!</p>
			</div>
    </div>
  </div>
</div>

<div class="turn">
	<div class="container">
		<div class="turn-header">
			<h1>Choose the box that's right for you.</h1>
		</div>
	  <div class="row">
		  <div class="col-lg-4">
				<div class="col-container">
					<div class="col-header">the original box noir</div>
		      <span class="col-ic col-ctail"></span>
					<div class="col-bottom">
			      <p class="col-p">
							Receive 2 cocktails, complimentary wine and beer every month
						</p>
						<%= link_to(reserve_url) do %>		
							<span class="btn btn-info">Reserve this Box</span>
						<% end %>
					</div>
				</div>
	    </div>
	    <div class="col-lg-4">
				<div class="col-container">
					<div class="col-header">wine taster subscription</div>
		      <span class="col-ic col-wine"></span>
					<div class="col-bottom">
			      <p class="col-p">
							Receive 3 bottles of handpicked fine wines every month
						</p>
						<%= link_to(reserve_url) do %>		
							<span class="btn btn-info">Reserve this Box</span>
						<% end %>					
					</div>
				</div>
	    </div>
	    <div class="col-lg-4">
				<div class="col-container">
					<div class="col-header">beer enthusiast subscription</div>
		      <span class="col-ic col-beer"></span>
					<div class="col-bottom">
			      <p class="col-p">
							Receive 6 new and exotic, craft, and imported beers every month
						</p>
						<%= link_to(reserve_url) do %>		
							<span class="btn btn-info">Reserve this Box</span>
						<% end %>
					</div>
				</div>
	   </div>
	  </div>
		<div class="turn-footer">
			<p>The Box Noir ships on the 10th of every month.</p>
		</div>
	</div>
</div>

<div class="prestige">
	<div class="container">
		<div class="prestige-body">
			<h1>Inside the box</h1><br />
			<p>
				Inside every box is a one-of-a-kind education. We don't just send you sample sizes bottles. With each box, we're helping you build a collection you'll be proud to show and serve to your friends, family, and guests. 
				<br /><br />
				Look forward to seasonal surprises such as barware, exclusive recipes, and <b>Noir’s Guide to Drinking</b> (a glossary of drinking terms and a look into the history of alcohol). 
			</p>
			<br /><br />
			<p>
				<%= link_to(reserve_url) do %>			
					<span class="btn btn-primary">reserve a box</span>
				<% end %>
			</p>
		</div>
	</div>
</div>

<%= render(:partial => 'partials/footer') -%>

app/views/welcome/reserve.html.erb
<%= render(:partial => 'partials/bar') -%>
<div class="navbar navbar-alt">
	<div class="container">
		<%= link_to(root_url) do %>
			<%= image_tag('logo.png', :id => 'nav-logo-alt')%>
		<% end %>
  </div>
</div>
<div id="turn-one" class="turn">
	<div class="container">
		<div class="turn-header">
			<%= form_for @waitlist, remote: true do |f| %>
			<h1>1. Enter your email address.</h1>
				<%= f.email_field :email_address, placeholder: 'your email address', class:'form-control', value: params[:email], autofocus: 'autofocus' %>
			<hr>
		</div>
		<div class="turn-header">
			<h1>2. Who is the box for?</h1>
			<%= f.fields_for :gender, @waitlist.gender do |s| %>		
				<div class="row row-form">
				<div class="col-lg-4">
					<%= s.check_box :man, class: 'col-checkbox' %>
					<label for="waitlist_gender_man">
						<h1>Man</h1>
					</label>
				</div>
				<div class="col-lg-4">
					<%= s.check_box :woman, class: 'col-checkbox' %>
					<label for="waitlist_gender_woman">
						<h1>Woman</h1>
					</label>
				</div>			
			</div>
			<% end %>
			<hr>
		</div>

		<div class="turn-header">
			<h1>3. Choose the boxes you'd like to reserve.</h1>
			<%= f.fields_for :type, @waitlist.type do |s| %>
				<div class="row row-form">
				<div class="col-lg-4">
					<%= s.check_box :ctailbox, class: 'col-checkbox' %>
					<label for="waitlist_type_ctailbox">
						<h1>The Original Box Noir</h1>
						<p>Receive 2 cocktails (w/ingredients) and complimentary wine and beer every month</p>
					</label>
				</div>
				<div class="col-lg-4">
					<%= s.check_box :winebox, class: 'col-checkbox' %>
					<label for="waitlist_type_winebox">
						<h1>Wine Taster Box</h1>
						<p>Receive 3 bottles of hand-picked fine wines every month</p>
					</label>
				</div>
				<div class="col-lg-4">
					<%= s.check_box :beerbox, class: 'col-checkbox' %>	
					<label for="waitlist_type_beerbox">
						<h1>Beer Enthusiast Box</h1>
						<p>Receive 6 new and exotic, craft, and imported beers every month</p>
					</label>
				</div>
			</div>
		</div>
	  <div class="turn-header">
				<hr>
				<%= f.submit "reserve my box", :class => 'btn btn-primary btn-lg' %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>
<div id="turn-two" class="turn">
	<div class="container">
		<div class="turn-header">
			<h1>Thanks for your reservation!</h1><br />
			<p>
				A sincere thanks for giving our product a try. A confirmation has been sent to your email. <br />
				The Box Noir ships on the 10th of every month. <br />
			</p> 
			<hr>
		</div>
	</div>
</div>
<div class="turn">
	<div class="container">
		<div class="turn-header">
		<h1 style="text-align:center;">What happens next?</h1>
	</div>
		<div class="row">
	    <div class="col-lg-4">
				<div class="col-container">				
		      <span class="col-ic col-email"></span>
					<div class="col-bottom">
			      <p class="col-p">
							Once your subscription is ready, we will send you an email with a link to claim your subscription. 
						</p>
					</div>
				</div>
	    </div>
	    <div class="col-lg-4">
				<div class="col-container">
		      <span class="col-ic col-comp"></span>
					<div class="col-bottom">
			      <p class="col-p">
							Enter your delivery information and create your taster's profile so we can start learning what you like.
						</p>
					</div>
				</div>
	   	</div>
    	<div class="col-lg-4">
				<div class="col-container">	
		      <span class="col-ic col-truck"></span>
					<div class="col-bottom">
			      <p class="col-p">
							Sit back and relax while we deliver a box of fine drinks and other goodies straight to your doorstep every month. 
						</p>
					</div>
				</div>
    	</div>
  </div>
		<div class="turn-header">
			<hr>
				<a href="https://www.facebook.com/theboxnoir" rel="nofollow" target="_BLANK">
					<div class="btn btn-lg btn-fb">like us on facebook</div>
				</a>
				<a href="https://twitter.com/TheBoxNoir" rel="nofollow" target="_BLANK">
					<div class="btn btn-lg btn-tw">follow us on twitter</div>
				</a>
		</div>
	</div>
</div>
<%= render(:partial => 'partials/footer') -%>