config/routes.rb
TheBoxNoir::Application.routes.draw do

	root to: "welcome#index"
	
	get '/reserve', :to => 'welcome#reserve'
	get '/login', :to => 'session#new'
  
  
  get '/about', :to => 'about#index'
	get '/faq', :to => 'about#faq'
	get '/careers', :to => 'about#careers'
  
    resources :reference
	resources :users
	resources :products
	
	resources :waitlists

	resources :session

  

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password validations: false #Validations for presence of password on create, confirmation of password (using a password_confirmation attribute) are automatically added. If you wish to turn off validations, pass validations: false as an argument. You can add more validations by hand if need be. 

	validates :password,
		:length => {:in => 5..30},
		:format => {:with => /\A\S*$\z/},
		:presence => {:on => :create}
end

app/models/waitlist.rb
class Waitlist < ActiveRecord::Base

#serialize :gender, :type


validates :email_address,
	presence: true,
	uniqueness: true,
	format: {with: /\A.+@.+\..+/}

validates :gender,
	presence: false,
	inclusion: { in: %w(male female) },
	allow_nil: true
	
validates :type,
  presence: true,
  inclusion: { in: %w(winebox beerbox ctailbox) },
  allow_nil: true
	
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout 'about'
  
  def index
  end
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

def create
  user = User.find_by_email_address(params[:session][:email_address])
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
		redirect_to :back
  else
    flash.now[:alert] = "Invalid email or password"
    render "new"
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
end

def create
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  
  def index
		@waitlist = Waitlist.new
  end
  def reserve
		@waitlist = Waitlist.new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reference_helper.rb
module ReferenceHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/about.html.erb
<% content_for :stylesheets do %>
	<%= stylesheet_link_tag 'about' -%>
<% end %>


<% content_for :content do %>
	<div id="wrap">
     <%= render(:partial => 'partials/bar') -%>
		<div class="navbar navbar-alt">
			<div class="container">
				<%= link_to(root_path) do %>
					<%= image_tag('logo.png', :id => 'nav-logo-alt')%>
				<% end %>
		  </div>
		</div>	
		<div class="container">	
			<div class="row row-offcanvas row-offcanvas-right">
				<%= yield %>	
		  	<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
		      <div class="well sidebar-nav">
						<%= link_to(reserve_path) do %>
							<span class="btn btn-primary btn-xs">Reserve a Box</span>
						<% end %>
		        <ul class="about-nav nav">
		          <li><%= link_to('Our Story', about_path)%></li>
		          <li><%= link_to('FAQ', faq_path)%></li>
		          <li><%= link_to('Careers', careers_path)%></li>
		        </ul>
		      </div><!--/.well -->
		    </div><!--/span-->
			</div>
		</div>
	</div>		
	<%= render(:partial => 'partials/footer') -%>
<% end %>

<%= render :template => 'layouts/template/application' -%>

app/views/layouts/session.html.erb
<% content_for :stylesheets do %>
	<%= stylesheet_link_tag 'session' -%>
<% end %>


<% content_for :content do %>
	<div id="session">
		<%= render(:partial => 'partials/bar') -%>
		<div class="navbar navbar-alt navbar-opaque">
			<div class="container">
				<%= image_tag('logo.png', :id => 'nav-logo-alt')%>
		  </div>
		</div>
		<div class="container">
			<%= yield %>
		</div>
	</div>		
<% end %>

<%= render :template => 'layouts/template/application' -%>

app/views/layouts/template/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<html lang="en">
  <head>
    <title><%= yield(:title) -%></title>	
    <meta charset="utf-8">		
    <%= csrf_meta_tags %> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="The Box Noir is an education in the art of drinking. Try our monthly subscription service of wines, beers, and spirits. No more guesswork, no more bad advice, just damn good drinks delivered to your doorstep.">    
		<%= favicon_link_tag 'favicon.ico', :type => 'image/x-icon' %>
    <meta name="viewport" content="width=800" user-scalable="no">
    <meta property="fb:app_id" content="635563316465519"/>
    <meta property="og:site_name" content="The Box Noir"/>
    <meta property="og:description" name="og:description" content="The Box Noir is an education in the art of drinking. Try our monthly subscription service of wines, beers, and spirits. No more guesswork, no more bad advice, just damn good drinks delivered to your doorstep."/>
    <meta property="og:type" content="website"/>
		<meta property="og:url" content="http://theboxnoir.com"/>
		<meta property="og:image" content="http://s3.amazonaws.com/theboxnoir/assets/og.png" />
    <link rel="apple-touch-icon-precomposed" href="<%= image_path 'apple-icon-precomposed.png' %>">
    <%= stylesheet_link_tag 'bootstrap', 'application', 'bootstrap-theme', 'media' -%>
    <%= yield(:stylesheets) -%>
    <%= javascript_include_tag 'application' -%>
  </head>
	<body>			
		
			<!--[if lt IE 7]>
	        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
	    <![endif]-->

    	<%= yield(:content) -%>
		
			<script>
				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

				ga('create', 'UA-44993632-1', 'theboxnoir.com');
				ga('send', 'pageview');
			</script>
	</body>
</html>

app/views/layouts/welcome.html.erb
<% content_for(:title, 'The Box Noir: The Finest Way to Drink') %>

<% content_for :stylesheets do %>
	<%= stylesheet_link_tag 'welcome' -%>
<% end %>

<% content_for :content do %>
	<%= yield -%>
<% end %>

<%= render :template => 'layouts/template/application' -%>

app/views/partials/_bar.html.erb
<div class="navbar">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
	        <li><span class="sprite-lock"></span><b>100% Secure</b></li>
					<li><a href="tel:18006185605">+1 (800) 618 5605</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to('FAQ', faq_path)%></li>
					<li>/</li>
          <li><%= link_to('Our Story', about_path)%></li>
					<li>/</li>
          <li><a href="#">Shopping Bag</a></li>
					<li>/</li>
          <li><%= link_to('Login', login_path)%></li>
        </ul>
      </div><!--/.navbar-collapse -->  	
	</div>
</div>

app/views/partials/_footer.html.erb
<footer>
  <div class="container">
		<div class="footer-left">
			<ul class="footer-column">
				<li class="footer-column-header">Company</li>
				<li><%= link_to('About', about_path)%></li>
        <li><%= link_to('FAQ', faq_path)%></li>
        <li><%= link_to('Careers', careers_path)%></li>
			</ul>
			<ul class="footer-column">
				<li class="footer-column-header">Support</li>
				<li>
					<b style="display:block;"><a href="tel:18006185605">+1 (800) 618 5605</a></b>
					<p>M-F 9AM-5PM PST</p><br />
					<a style="display:block;" href="mailto:info@theboxnoir.com"><u>info@theboxnoir.com</u></a>
				</li>
			</ul>
		</div>
		<div class="footer-right">
			<div class="footer-social">
				<a href="https://www.facebook.com/theboxnoir" rel="nofollow" target="_BLANK"><span class="footer-social-icon sprite-fb"></span></a>
				<a href="https://twitter.com/TheBoxNoir" rel="nofollow" target="_BLANK"><span class="footer-social-icon sprite-tw"></span></a>
			</div>
			<div class="footer-copy">
				<p>&copy; The Box Noir Inc. 2014</p>
				<p>
					Privacy Policy | Terms of Service
				</p>
			</div>
		</div>
	</div>
</footer>